# Generated by Django 5.0 on 2023-12-05 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Код')),
                ('currency_rate', models.DecimalField(decimal_places=6, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('code', models.CharField(max_length=3, verbose_name='Код')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('converter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('rate', models.ManyToManyField(to='converter.currencyrate', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'Конвертер валют',
                'verbose_name_plural': 'Конвертеры валют',
            },
        ),
    ]
